export const SET_GET_PROJECT_CATEGORY = "SET_GET_PROJECT_CATEGORY"
export const SET_GET_ALL_PROJECTS = "SET_GET_ALL_PROJECTS";

export const SET_GET_PROJECT_DETAIL= "SET_GET_PROJECT_DETAIL";
export const SET_GET_TASK_DETAIL= "SET_GET_TASK_DETAIL";

export const CHANGE_VALUE_MODAL = "CHANGE_VALUE_MODAL";
export const GET_PROJECT_SEARCH = "GET_PROJECT_SEARCH";