export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';

export const SET_GET_LIST_USERS = 'SET_GET_LIST_USERS';

export const SET_GET_USER_DETAIL = 'SET_GET_USER_DETAIL';
export const SET_GET_USER_BY_PROJECT = 'SET_GET_USER_BY_PROJECT';

export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';